use_frameworks!

target 'automonetize_Example' do
  pod 'automonetize', :path => '../'

  target 'automonetize_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
